"""Change auth_config to JSON

Revision ID: 7e6085d416af
Revises: c273795d367a
Create Date: 2025-10-13 14:16:46.746803

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7e6085d416af"
down_revision: Union[str, Sequence[str], None] = "c273795d367a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "carrier",
        "type",
        existing_type=postgresql.ENUM(
            "api", "webhook", "scraper", "manual", name="carriertype"
        ),
        nullable=False,
    )
    op.alter_column(
        "carrier", "auth_config", type_=sa.JSON(), postgresql_using="auth_config::json"
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "carrier",
        "auth_config",
        existing_type=sa.JSON(),
        type_=sa.VARCHAR(length=200),
        existing_nullable=True,
    )
    op.alter_column(
        "carrier",
        "type",
        existing_type=postgresql.ENUM(
            "api", "webhook", "scraper", "manual", name="carriertype"
        ),
        nullable=True,
    )
    # ### end Alembic commands ###
