"""Add location table

Revision ID: a72459cd542c
Revises: ce2c5ba014a4
Create Date: 2025-10-03 20:55:28.705197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a72459cd542c'
down_revision: Union[str, Sequence[str], None] = 'ce2c5ba014a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cache',
    sa.Column('cache_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('data', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('cache_id')
    )
    op.create_index(op.f('ix_cache_cache_id'), 'cache', ['cache_id'], unique=False)
    op.create_table('carrier',
    sa.Column('carrier_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('base_url', sa.String(), nullable=True),
    sa.Column('api_endpoint', sa.String(length=200), nullable=True),
    sa.Column('auth_config', sa.String(length=200), nullable=True),
    sa.Column('has_webhook', sa.Boolean(), nullable=True),
    sa.Column('carrier_metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('carrier_id')
    )
    op.create_index(op.f('ix_carrier_carrier_id'), 'carrier', ['carrier_id'], unique=False)
    op.create_index(op.f('ix_carrier_code'), 'carrier', ['code'], unique=True)
    op.create_table('location',
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.String(length=100), nullable=True),
    sa.Column('longitude', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('location_id')
    )
    op.create_index(op.f('ix_location_location_id'), 'location', ['location_id'], unique=False)
    op.create_table('merchant',
    sa.Column('merchant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('api_key', sa.String(length=50), nullable=False),
    sa.Column('webhook_url', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('merchant_id')
    )
    op.create_index(op.f('ix_merchant_merchant_id'), 'merchant', ['merchant_id'], unique=False)
    op.create_table('users',
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('customer_id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_customer_id'), 'users', ['customer_id'], unique=False)
    op.create_table('analytics',
    sa.Column('analytics_id', sa.Integer(), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=True),
    sa.Column('delivery_time', sa.Date(), nullable=False),
    sa.Column('on_time_percentage', sa.Date(), nullable=False),
    sa.Column('carrier_id', sa.Integer(), nullable=True),
    sa.Column('failed_deliveries', sa.Date(), nullable=False),
    sa.Column('avg_response_time', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['carrier_id'], ['carrier.carrier_id'], ),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchant.merchant_id'], ),
    sa.PrimaryKeyConstraint('analytics_id')
    )
    op.create_index(op.f('ix_analytics_analytics_id'), 'analytics', ['analytics_id'], unique=False)
    op.create_table('shipment',
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('merchant_id', sa.Integer(), nullable=True),
    sa.Column('carrier_tracking_id', sa.String(length=50), nullable=False),
    sa.Column('universal_id', sa.String(length=50), nullable=False),
    sa.Column('carrier_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_update', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expected_delivery', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['carrier_id'], ['carrier.carrier_id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['users.customer_id'], ),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchant.merchant_id'], ),
    sa.PrimaryKeyConstraint('shipment_id')
    )
    op.create_index(op.f('ix_shipment_shipment_id'), 'shipment', ['shipment_id'], unique=False)
    op.create_table('user_preference',
    sa.Column('user_pref_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=20), nullable=True),
    sa.Column('subtitle_preference', sa.String(length=20), nullable=True),
    sa.Column('notification_preferences', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['users.customer_id'], ),
    sa.PrimaryKeyConstraint('user_pref_id')
    )
    op.create_index(op.f('ix_user_preference_user_pref_id'), 'user_preference', ['user_pref_id'], unique=False)
    op.create_table('notification',
    sa.Column('notification_id', sa.Integer(), nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=True),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipment.shipment_id'], ),
    sa.PrimaryKeyConstraint('notification_id')
    )
    op.create_index(op.f('ix_notification_notification_id'), 'notification', ['notification_id'], unique=False)
    op.create_table('tracking_event',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('tracking_id', sa.String(), nullable=True),
    sa.Column('shipment_id', sa.Integer(), nullable=True),
    sa.Column('carrier_code', sa.String(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['location.location_id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipment.shipment_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_tracking_event_carrier_code'), 'tracking_event', ['carrier_code'], unique=False)
    op.create_index(op.f('ix_tracking_event_event_id'), 'tracking_event', ['event_id'], unique=False)
    op.create_index(op.f('ix_tracking_event_tracking_id'), 'tracking_event', ['tracking_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tracking_event_tracking_id'), table_name='tracking_event')
    op.drop_index(op.f('ix_tracking_event_event_id'), table_name='tracking_event')
    op.drop_index(op.f('ix_tracking_event_carrier_code'), table_name='tracking_event')
    op.drop_table('tracking_event')
    op.drop_index(op.f('ix_notification_notification_id'), table_name='notification')
    op.drop_table('notification')
    op.drop_index(op.f('ix_user_preference_user_pref_id'), table_name='user_preference')
    op.drop_table('user_preference')
    op.drop_index(op.f('ix_shipment_shipment_id'), table_name='shipment')
    op.drop_table('shipment')
    op.drop_index(op.f('ix_analytics_analytics_id'), table_name='analytics')
    op.drop_table('analytics')
    op.drop_index(op.f('ix_users_customer_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_merchant_merchant_id'), table_name='merchant')
    op.drop_table('merchant')
    op.drop_index(op.f('ix_location_location_id'), table_name='location')
    op.drop_table('location')
    op.drop_index(op.f('ix_carrier_code'), table_name='carrier')
    op.drop_index(op.f('ix_carrier_carrier_id'), table_name='carrier')
    op.drop_table('carrier')
    op.drop_index(op.f('ix_cache_cache_id'), table_name='cache')
    op.drop_table('cache')
    # ### end Alembic commands ###
