"""add tracking_events table

Revision ID: c273795d367a
Revises: a72459cd542c
Create Date: 2025-10-09 14:38:02.034887
"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c273795d367a"
down_revision: Union[str, Sequence[str], None] = "a72459cd542c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ✅ Create enum types explicitly before using them
    carrier_status_enum = sa.Enum(
        "active", "inactive", "maintenance", name="carrierstatus"
    )
    carrier_status_enum.create(op.get_bind(), checkfirst=True)

    carrier_type_enum = sa.Enum(
        "api", "webhook", "scraper", "manual", name="carriertype"
    )
    carrier_type_enum.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - adjusted ###
    op.create_table(
        "carrier_webhooks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("carrier_id_ref", sa.Integer(), nullable=False),
        sa.Column("event_type", sa.String(length=50), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=True),
        sa.Column("last_attempt", sa.DateTime(), nullable=True),
        sa.Column("next_attempt", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("processed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["carrier_id_ref"], ["carrier.carrier_id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_carrier_webhooks_id"), "carrier_webhooks", ["id"], unique=False
    )

    op.add_column("carrier", sa.Column("description", sa.Text(), nullable=True))
    op.add_column(
        "carrier",
        sa.Column(
            "status", carrier_status_enum, nullable=False, server_default="active"
        ),
    )
    op.add_column(
        "carrier", sa.Column("auth_type", sa.String(length=50), nullable=True)
    )
    op.add_column(
        "carrier", sa.Column("webhook_verification", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "carrier", sa.Column("webhook_url", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "carrier", sa.Column("webhook_secret", sa.String(length=255), nullable=True)
    )
    op.add_column("carrier", sa.Column("scraper_config", sa.JSON(), nullable=True))
    op.add_column("carrier", sa.Column("requires_js", sa.Boolean(), nullable=True))
    op.add_column(
        "carrier",
        sa.Column("tracking_url_template", sa.String(length=255), nullable=True),
    )
    op.add_column(
        "carrier",
        sa.Column("tracking_id_pattern", sa.String(length=100), nullable=True),
    )
    op.add_column("carrier", sa.Column("country", sa.String(length=50), nullable=True))
    op.add_column(
        "carrier", sa.Column("support_phone", sa.String(length=20), nullable=True)
    )
    op.add_column(
        "carrier", sa.Column("support_email", sa.String(length=100), nullable=True)
    )
    op.add_column("carrier", sa.Column("is_active", sa.Boolean(), nullable=True))
    op.add_column(
        "carrier",
        sa.Column(
            "created_at", sa.DateTime(), nullable=False, server_default=sa.func.now()
        ),
    )
    op.add_column(
        "carrier",
        sa.Column(
            "updated_at", sa.DateTime(), nullable=False, server_default=sa.func.now()
        ),
    )

    # Explicitly cast VARCHAR to ENUM using USING clause
    op.execute(
        "ALTER TABLE carrier ALTER COLUMN type TYPE carriertype USING type::carriertype"
    )

    op.drop_column("carrier", "has_webhook")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.add_column(
        "carrier",
        sa.Column("has_webhook", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    op.alter_column(
        "carrier",
        "type",
        existing_type=sa.Enum(
            "api", "webhook", "scraper", "manual", name="carriertype"
        ),
        type_=sa.VARCHAR(),
        nullable=True,
    )
    op.drop_column("carrier", "updated_at")
    op.drop_column("carrier", "created_at")
    op.drop_column("carrier", "is_active")
    op.drop_column("carrier", "support_email")
    op.drop_column("carrier", "support_phone")
    op.drop_column("carrier", "country")
    op.drop_column("carrier", "tracking_id_pattern")
    op.drop_column("carrier", "tracking_url_template")
    op.drop_column("carrier", "requires_js")
    op.drop_column("carrier", "scraper_config")
    op.drop_column("carrier", "webhook_secret")
    op.drop_column("carrier", "webhook_url")
    op.drop_column("carrier", "webhook_verification")
    op.drop_column("carrier", "auth_type")
    op.drop_column("carrier", "status")
    op.drop_column("carrier", "description")
    op.drop_index(op.f("ix_carrier_webhooks_id"), table_name="carrier_webhooks")
    op.drop_table("carrier_webhooks")

    # ✅ Drop the enums on downgrade
    carrier_status_enum = sa.Enum(
        "active", "inactive", "maintenance", name="carrierstatus"
    )
    carrier_status_enum.drop(op.get_bind(), checkfirst=True)

    carrier_type_enum = sa.Enum(
        "api", "webhook", "scraper", "manual", name="carriertype"
    )
    carrier_type_enum.drop(op.get_bind(), checkfirst=True)
