"""add tracking_events table

Revision ID: ce2c5ba014a4
Revises: 562c8c2ed42f
Create Date: 2025-09-25 23:23:12.249652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce2c5ba014a4'
down_revision: Union[str, Sequence[str], None] = '562c8c2ed42f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carrier', sa.Column('code', sa.String(), nullable=True))
    op.add_column('carrier', sa.Column('has_webhook', sa.Boolean(), nullable=True))
    op.add_column('carrier', sa.Column('carrier_metadata', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_carrier_code'), 'carrier', ['code'], unique=True)
    op.add_column('tracking_event', sa.Column('tracking_id', sa.String(), nullable=True))
    op.add_column('tracking_event', sa.Column('carrier_code', sa.String(), nullable=True))
    op.add_column('tracking_event', sa.Column('raw_payload', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_tracking_event_carrier_code'), 'tracking_event', ['carrier_code'], unique=False)
    op.create_index(op.f('ix_tracking_event_tracking_id'), 'tracking_event', ['tracking_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tracking_event_tracking_id'), table_name='tracking_event')
    op.drop_index(op.f('ix_tracking_event_carrier_code'), table_name='tracking_event')
    op.drop_column('tracking_event', 'raw_payload')
    op.drop_column('tracking_event', 'carrier_code')
    op.drop_column('tracking_event', 'tracking_id')
    op.drop_index(op.f('ix_carrier_code'), table_name='carrier')
    op.drop_column('carrier', 'carrier_metadata')
    op.drop_column('carrier', 'has_webhook')
    op.drop_column('carrier', 'code')
    # ### end Alembic commands ###
