"""Fix carrier type enum to lowercase

Revision ID: f577aeb06e03
Revises: 95f33c7a2bd2
Create Date: 2025-10-13 16:16:44.160370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f577aeb06e03'
down_revision: Union[str, Sequence[str], None] = '95f33c7a2bd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
